name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3000/api/v1/
          NEXT_PUBLIC_LOGGING_LEVEL: 0
          NEXT_PUBLIC_USER_NAME: Simard

          MONGO_DB_URL_LOCAL: ${{ secrets.MONGO_DB_URL_LOCAL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_GPT_MODEL: ${{ secrets.OPENAI_GPT_MODEL }}
          BLOCK_OPEN_AI_API_CALLS: ${{ secrets.BLOCK_OPEN_AI_API_CALLS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run build

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=simardcodetard \
            -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECT_KEY }} \
            -Dsonar.sources=./app \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            
            # Fail the step if sonar status is not 'OK'
            STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONARCLOUD_PROJECT_KEY }}" | jq -r .projectStatus.status)
            
            # Fail the step if new code contains issues at least as severe as 'MEDIUM'
            MAJOR_ISSUES=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${{ secrets.SONARCLOUD_PROJECT_KEY }}&severities=MAJOR&types=BUG,CODE_SMELL,VULNERABILITY&resolved=false&sinceLeakPeriod=true" \
            | jq -r ".total")

            echo "🔍 Major issues in new code: $MAJOR_ISSUES"

            # Si au moins 1 problème de gravité "Major" est détecté, on bloque la PR
            if [ "$MAJOR_ISSUES" -gt 0 ]; then
              echo "❌ New major issues detected! PR blocked."
              exit 1
            else
              echo "✅ No new major issues found."
            fi
